"""add receipt_pdf column

Revision ID: a3e62e16cb44
Revises: 
Create Date: 2026-08-04 20:12:23.038326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e62e16cb44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('razorpay_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_fee', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('razorpay_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('razorpay_contact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('razorpay_raw_payload', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receipt_pdf', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('receipt_pdf')
        batch_op.drop_column('razorpay_raw_payload')
        batch_op.drop_column('razorpay_contact')
        batch_op.drop_column('razorpay_email')
        batch_op.drop_column('razorpay_fee')
        batch_op.drop_column('razorpay_reference')
        batch_op.drop_column('razorpay_method')

    # ### end Alembic commands ###
